name: Test AML Dashboard

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        
    - name: Run linting
      run: |
        pip install flake8 black
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        black --check .
        
    - name: Test Docker build
      run: |
        docker build -f docker/Dockerfile -t aml-dashboard-test .
        
    - name: Test Docker run
      run: |
        docker run -d --name aml-test -p 8502:8501 aml-dashboard-test
        sleep 30
        curl -f http://localhost:8502 || exit 1
        docker stop aml-test
        docker rm aml-test 